### ISSUE TITLE
Path Issue

### ISSUE THREAD

**Issue by abeperl** [lmiller1990/vue_tsx_article_demo#1]
https://github.com/lmiller1990/vue_tsx_article_demo/blob/6e69ebe7730bc16e9e876d1ace5600c48ff8678d/src/main.ts#L3

think it should be, or am i wrong
import { store } from '@/store/index'

same in App.tsx

**Comment by EvanBurbidge** [comment]
@abeperl  if its an index.ts file or .js then this should be fine as usually the index is used as a "barrel" file to import / export things which allows you an entry point into a folder without specifying import x from '/a/b/c' you could just export that member in the index of A and then you'd say import x from '/a'

**Comment by lmiller1990** [comment]
Right - like @EvanBurbidge said, if you import a directory, node will automatically look for an `index` file.  TypeScript does this too. This also works with `index.vue` files.

Are you having trouble getting the demo to run locally?
